"use client";

import { useState } from "react";
import { ethers } from "ethers";

declare global {
    interface Window {
        ethereum?: any;
          }
          }

const CONTRACT_ADDRESS = "0xbA3Df320996eed030a418413e239be44f28C0e3F";

const ABI = [
  "function stake(uint256 amount) external",
    "function unstake(uint256 amount) external",
      "function claim() external",
        "function balanceOf(address) view returns (uint256)"
        ];

        export default function Home() {
          const [account, setAccount] = useState("");
            const [amount, setAmount] = useState("");

              async function connectWallet() {
                  if (!window.ethereum) return alert("Install MetaMask");
                      const provider = new ethers.BrowserProvider(window.ethereum);
                          const accounts = await provider.send("eth_requestAccounts", []);
                              setAccount(accounts[0]);
                                }

                                  async function getContract() {
                                      const provider = new ethers.BrowserProvider(window.ethereum);
                                          const signer = await provider.getSigner();
                                              return new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
                                                }

                                                  async function stake() {
                                                      const contract = await getContract();
                                                          const tx = await contract.stake(
                                                                ethers.parseUnits(amount, 18)
                                                                    );
                                                                        await tx.wait();
                                                                            alert("Stake successful");
                                                                              }

                                                                                async function claim() {
                                                                                    const contract = await getContract();
                                                                                        const tx = await contract.claim();
                                                                                            await tx.wait();
                                                                                                alert("Reward claimed");
                                                                                                  }

                                                                                                    async function unstake() {
                                                                                                        const contract = await getContract();
                                                                                                            const tx = await contract.unstake(
                                                                                                                  ethers.parseUnits(amount, 18)
                                                                                                                      );
                                                                                                                          await tx.wait();
                                                                                                                              alert("Unstake successful");
                                                                                                                                }

                                                                                                                                  return (
                                                                                                                                      <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-black via-slate-900 to-black text-white">

                                                                                                                                            <div className="w-full max-w-xl p-8 rounded-2xl backdrop-blur-xl bg-white/5 border border-cyan-500/30 shadow-[0_0_40px_rgba(0,255,255,0.15)]">

                                                                                                                                                    <h1 className="text-3xl font-bold text-center text-cyan-400 mb-6 tracking-wider">
                                                                                                                                                              AUTHEO STAKING
                                                                                                                                                                      </h1>

                                                                                                                                                                              {!account ? (
                                                                                                                                                                                        <button
                                                                                                                                                                                                    onClick={connectWallet}
                                                                                                                                                                                                                className="w-full py-3 rounded-xl bg-cyan-500 hover:bg-cyan-400 font-semibold shadow-[0_0_20px_rgba(0,255,255,0.6)]"
                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                      Connect Wallet
                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                              <div className="mb-6 text-center text-sm text-gray-400">
                                                                                                                                                                                                                                                                                            Connected: <span className="text-cyan-400">{account.slice(0,6)}...{account.slice(-4)}</span>
                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                  placeholder="Amount to stake"
                                                                                                                                                                                                                                                                                                                                                value={amount}
                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setAmount(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                            className="w-full mb-4 px-4 py-3 rounded-xl bg-slate-800 border border-cyan-500/30 focus:outline-none focus:border-cyan-400"
                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-3 gap-3">

                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={stake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="py-3 rounded-xl bg-green-600 hover:bg-green-500 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Stake
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={claim}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="py-3 rounded-xl bg-yellow-500 hover:bg-yellow-400 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Claim
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={unstake}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="py-3 rounded-xl bg-red-600 hover:bg-red-500 font-semibold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Unstake
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }